In [1]:
import numpy as np
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [2]:
# get specific element [row, coloumn]
a[1,5]
# python is zero index

13

In [4]:
# get specific row
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [5]:
# get specific coloumn
a[:, 2]

array([ 3, 10])

In [7]:
# get little bit more fancy [startindex:endindex:stepsize]
# second row , second element to fifth element 2 step
a[1, 1:5:2]

array([ 9, 11])

In [8]:
# change element
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [9]:
a[:,2] = [1, 2]  # : means every row here and 2 means third coloum
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [11]:
# 3-d example
c = np.array([[[1,2], [3, 4]],[[5, 6], [7, 8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
# get specific element (work outside in )
c[0, 0, 1]

2

In [17]:
c[0, 0, :]

array([[11, 18],
       [15, 17]])

In [16]:
# replace
c[: , 1, :] = [[11, 18],[15, 17]]
print(c)

[[[ 1  2]
  [11 18]]

 [[ 5  6]
  [15 17]]]
