In [7]:
import numpy as np

In [8]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# All 1s matrix
np.ones((4, 2))

np.ones((4, 2), dtype="int32")
# np.ones((4, 2), dtype="float32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [14]:
# any other number
np.full((2, 3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [17]:
# any other number full_like
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
np.full_like(a, 15)

# or

np.full(a.shape, 16)

array([[16, 16, 16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16, 16, 16]])

In [19]:
# random decimal numbers
np.random.rand(4, 2)
np.random.rand(4, 2, 3)

array([[[0.15898627, 0.42928615, 0.12082402],
        [0.67865388, 0.29669921, 0.31536756]],

       [[0.67343546, 0.92374984, 0.96898894],
        [0.69935268, 0.50107213, 0.14689213]],

       [[0.58913523, 0.24449904, 0.87131601],
        [0.10353118, 0.03641683, 0.88959544]],

       [[0.02348283, 0.12048334, 0.04865497],
        [0.51634826, 0.68042099, 0.80249016]]])

In [20]:
# pass the shape in random
np.random.random_sample(a.shape)

array([[0.58960639, 0.53369196, 0.82098185, 0.80639915, 0.24608821,
        0.10168363, 0.34482896],
       [0.2737602 , 0.02240261, 0.49785319, 0.81897397, 0.42315864,
        0.52435358, 0.23258462]])

In [24]:
# random integer values
np.random.randint(8, size=(3, 3))
np.random.randint(5,8, size=(3, 3))
np.random.randint(5,8, size=(3, 3))

array([[6, 5, 5],
       [7, 7, 7],
       [7, 6, 6]])

In [25]:
# the identity matrix(square matrix)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# repeat matrix
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [27]:
arr = np.array([[1, 2, 3]])  # convert 2 dimensional array to create axis 0
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [34]:
m1 = np.zeros((3,3))
m1[1,1]= 9

m2 = np.ones((5,5))
m2[1:4, 1:4] = m1
# or m2[1:-1, 1:-1] = m1
print(m2)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [36]:
# copy array
a = np.array([1,2,3])
b = a.copy()  # if you not copy a is change forever aswell
b[1] = 100
print(b)

[  1 100   3]


In [ ]:
# more
# https://numpy.org/doc/stable/reference/routines.array-creation.html