In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4])


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [9]:
a ** 2

array([ 1,  4,  9, 16])

In [11]:
# take sin and cos
np.sin(a)
np.cos(a)

## more
# https://numpy.org/doc/stable/reference/routines.math.html

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [16]:
a = np.ones((2,3))
print(a)

b = np.full((3,3), 5)
print(b)

np.matmul(a,b)  # first matrix coloum and second matrix row must be same size

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


array([[15., 15., 15.],
       [15., 15., 15.]])

In [19]:
# find determinant
c = np.identity(3)
np.linalg.det(c)

# more 
# https://numpy.org/doc/stable/reference/routines.linalg.html

1.0

##### Statistic

In [20]:
stats = np.array([[1,2,3], [4,5,6]])
np.min(stats)

1

In [22]:
np.min(stats, axis=1)

array([1, 4])

In [24]:
np.max(stats, axis=1)

array([3, 6])

In [25]:
np.sum(stats)

21

In [27]:
np.sum(stats, axis=1)

array([ 6, 15])