In [1]:
import numpy as np

In [5]:
# load data from file
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[1.000e+00, 2.000e+00, 3.000e+00, 4.000e+00, 5.000e+00, 1.000e+02,
        5.500e+01, 6.500e+01, 5.000e+00, 2.000e+00, 3.000e+00, 4.000e+00],
       [8.000e+00, 7.000e+00, 9.000e+00, 4.000e+00, 1.100e+01, 2.110e+02,
        5.400e+01, 6.300e+01, 1.000e+00, 2.400e+01, 4.000e+00, 7.000e+00],
       [1.100e+01, 2.200e+01, 3.300e+01, 5.500e+01, 6.600e+01, 4.477e+03,
        7.700e+01, 8.800e+01, 1.400e+01, 2.500e+01, 1.400e+01, 1.500e+01]])

In [6]:
filedata = np.genfromtxt('data.txt', delimiter=',', dtype="int32")
filedata

array([[   1,    2,    3,    4,    5,  100,   55,   65,    5,    2,    3,
           4],
       [   8,    7,    9,    4,   11,  211,   54,   63,    1,   24,    4,
           7],
       [  11,   22,   33,   55,   66, 4477,   77,   88,   14,   25,   14,
          15]])

In [7]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[   1,    2,    3,    4,    5,  100,   55,   65,    5,    2,    3,
           4],
       [   8,    7,    9,    4,   11,  211,   54,   63,    1,   24,    4,
           7],
       [  11,   22,   33,   55,   66, 4477,   77,   88,   14,   25,   14,
          15]])

##### Boolean Masking and Advance indexing


In [8]:
filedata > 50

array([[False, False, False, False, False,  True,  True,  True, False,
        False, False, False],
       [False, False, False, False, False,  True,  True,  True, False,
        False, False, False],
       [False, False, False,  True,  True,  True,  True,  True, False,
        False, False, False]])

In [9]:
filedata[filedata > 50]  #  create an array

array([ 100,   55,   65,  211,   54,   63,   55,   66, 4477,   77,   88])

In [10]:
# indexing in numpy
arr = np.array([1,2,3,4,5,6,7,8])
arr[[1,2,7]]

array([2, 3, 8])

In [14]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [15]:
np.any(filedata > 50, axis=0)

array([False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False])

In [16]:
np.all(filedata > 50, axis=0)

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False])

In [17]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [18]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False,  True,  True, False,
        False, False, False],
       [False, False, False, False, False, False,  True,  True, False,
        False, False, False],
       [False, False, False,  True,  True, False,  True,  True, False,
        False, False, False]])

In [19]:
(~(filedata > 50) & (filedata < 100))  # ~ not operator

array([[ True,  True,  True,  True,  True, False, False, False,  True,
         True,  True,  True],
       [ True,  True,  True,  True,  True, False, False, False,  True,
         True,  True,  True],
       [ True,  True,  True, False, False, False, False, False,  True,
         True,  True,  True]])

In [ ]:
np.linspace(0, 25, 5)