In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])  # one dimensional array
print(a)

[1 2 3]


In [3]:
b = np.array([[1, 2, 3], [5.0, 6.0, 9.0]])  # two dimensional array
print(b)

[[1. 2. 3.]
 [5. 6. 9.]]


In [4]:
# Get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# Get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [8]:
# Get type
a.dtype

dtype('int32')

In [9]:
b.dtype

dtype('float64')

In [10]:
# get size
a.itemsize  # int32 and 4 bytes

4

In [11]:
b.itemsize  # float64 and 8 bytes

8

In [12]:
# get total size
a.nbytes

12