In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [5]:
# get 11,12,16,17

arr[2:4,:2]

array([[11, 12],
       [16, 17]])

In [7]:
# get 2,8,14,20
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [15]:
# get 4,5 24,25,29,30
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])