In [2]:
import numpy as np

In [5]:
before = np.array([[1,2,3,4], [5,6,7,8]])

after = before.reshape(2,4)
print(after)

after2 = before.reshape(8,1)
print(after2)

# dimensions need to be match

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [7]:
# vertically stacking vector or matrix

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# horizontal stack

h1 = np.zeros((2,3))
h2 = np.ones((2,4))

np.hstack((h1,h2))

array([[0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1.]])